openapi: 3.0.1
info:
  contact: {}
  description: Api Documentation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  termsOfService: urn:tos
  title: Api Documentation
  version: "1.0"
servers:
- url: http://10.0.2.2:8080/
tags:
- description: Web service API description for Music Quiz practice.
  name: songs-service
paths:
  /songs:
    get:
      deprecated: false
      description: Endpoint to return the whole list of songs.
      operationId: findAll
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Songs'
          description: OK
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
        "500":
          content: {}
          description: Server Error
      summary: findAll
      tags:
      - songs-service
      x-accepts: application/json
  /songs/{id}:
    get:
      deprecated: false
      description: Endpoint to get one song by its id.
      operationId: getById
      parameters:
      - description: Song id to retrieve.
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Song'
          description: OK
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
        "500":
          content: {}
          description: Server Error
      summary: getById
      tags:
      - songs-service
      x-accepts: application/json
components:
  schemas:
    Songs:
      items:
        $ref: '#/components/schemas/Song'
      type: array
    Song:
      example:
        lenght: 6
        file: file
        author: author
        name: name
        id: 0
      properties:
        id:
          format: int32
          nullable: false
          type: integer
        name:
          nullable: false
          type: string
        author:
          nullable: false
          type: string
        file:
          nullable: false
          type: string
        lenght:
          format: int64
          nullable: false
          type: integer
      type: object

